import {
  IdentityPool,
  UserPoolAuthenticationProvider,
} from 'aws-cdk-lib/aws-cognito-identitypool';
import { CfnOutput, Duration, Lazy, Stack } from 'aws-cdk-lib';
import {
  AccountRecovery,
  CfnManagedLoginBranding,
  CfnUserPoolDomain,
  Mfa,
  OAuthScope,
  ResourceServerScope,
  UserPool,
  UserPoolClient,
} from 'aws-cdk-lib/aws-cognito';
import { Construct } from 'constructs';
import { RuntimeConfig } from './runtime-config.js';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';
import { Distribution } from 'aws-cdk-lib/aws-cloudfront';
import { suppressRules } from './checkov.js';

const WEB_CLIENT_ID = 'WebClient';
/**
 * Creates a UserPool and Identity Pool with sane defaults configured intended for usage from a web client.
 */
export class UserIdentity extends Construct {
  public readonly region: string;
  public readonly identityPool: IdentityPool;
  public readonly userPool: UserPool;
  public readonly userPoolClient: UserPoolClient;
  public readonly userPoolDomain: CfnUserPoolDomain;
  public readonly executorClient: UserPoolClient;
  public readonly executorSecret: Secret;
  public readonly cognitoTokenEndpoint: string;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.region = Stack.of(this).region;
    this.userPool = this.createUserPool();
    this.userPoolDomain = this.createUserPoolDomain(this.userPool);
    this.userPoolClient = this.createUserPoolClient(this.userPool);
    this.identityPool = this.createIdentityPool(
      this.userPool,
      this.userPoolClient,
    );
    this.createManagedLoginBranding(
      this.userPool,
      this.userPoolClient,
      this.userPoolDomain,
    );

    // Resource server + executor client for client_credentials grant (scheduler executor Lambda)
    const schedulerScope = new ResourceServerScope({
      scopeName: 'execute',
      scopeDescription: 'Execute scheduled tasks',
    });
    const resourceServer = this.userPool.addResourceServer(
      'SchedulerResourceServer',
      {
        identifier: 'scheduler',
        scopes: [schedulerScope],
      },
    );

    this.executorClient = this.userPool.addClient('ExecutorClient', {
      oAuth: {
        flows: { clientCredentials: true },
        scopes: [OAuthScope.resourceServer(resourceServer, schedulerScope)],
      },
      generateSecret: true,
    });

    // Store executor client secret in Secrets Manager (Lambda reads on cold start)
    this.executorSecret = new Secret(this, 'ExecutorClientSecret', {
      secretStringValue: this.executorClient.userPoolClientSecret,
    });

    suppressRules(
      this.executorSecret,
      ['CKV_AWS_149'],
      'Cognito client secret encrypted with AWS-managed key (aws/secretsmanager). CMK not required — secret is auto-generated by Cognito, short-lived, rotatable, and contains no customer data.',
    );

    // Token endpoint derived from the existing Cognito domain
    const domain = `wealth-mgmt-portal-${Stack.of(this).account}`;
    this.cognitoTokenEndpoint = `https://${domain}.auth.${Stack.of(this).region}.amazoncognito.com/oauth2/token`;

    RuntimeConfig.ensure(this).config.cognitoProps = {
      region: Stack.of(this).region,
      identityPoolId: this.identityPool.identityPoolId,
      userPoolId: this.userPool.userPoolId,
      userPoolWebClientId: this.userPoolClient.userPoolClientId,
    };

    suppressRules(
      this.userPool,
      ['CKV_AWS_111'],
      'SMS Role requires wildcard resource',
      (c) => c.node.path.includes('/smsRole/'),
    );

    new CfnOutput(this, `${id}-UserPoolId`, {
      value: this.userPool.userPoolId,
    });

    new CfnOutput(this, `${id}-UserPoolClientId`, {
      value: this.userPoolClient.userPoolClientId,
    });

    new CfnOutput(this, `${id}-IdentityPoolId`, {
      value: this.identityPool.identityPoolId,
    });
  }

  private createUserPool = () =>
    new UserPool(this, 'UserPool', {
      deletionProtection: true,
      passwordPolicy: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireDigits: true,
        requireSymbols: true,
        tempPasswordValidity: Duration.days(3),
      },
      mfa: Mfa.OFF,
      signInCaseSensitive: false,
      signInAliases: { username: true, email: true },
      accountRecovery: AccountRecovery.EMAIL_ONLY,
      selfSignUpEnabled: false,
      standardAttributes: {
        phoneNumber: { required: false },
        email: { required: true },
        givenName: { required: true },
        familyName: { required: true },
      },
      autoVerify: {
        email: true,
        phone: true,
      },
      keepOriginal: {
        email: true,
        phone: true,
      },
    });

  private createUserPoolDomain = (userPool: UserPool) =>
    new CfnUserPoolDomain(this, 'UserPoolDomain', {
      domain: `wealth-mgmt-portal-${Stack.of(this).account}`,
      userPoolId: userPool.userPoolId,
      managedLoginVersion: 2,
    });

  private createUserPoolClient = (userPool: UserPool) => {
    const lazilyComputedCallbackUrls = Lazy.list({
      produce: () =>
        [
          'http://localhost:4200',
          'http://localhost:4300',
          `https://${Stack.of(this).region}.console.aws.amazon.com`,
        ].concat(
          this.findCloudFrontDistributions().map(
            (d) => `https://${d.domainName}`,
          ),
        ),
    });

    return userPool.addClient(WEB_CLIENT_ID, {
      authFlows: {
        userPassword: true,
        userSrp: true,
        user: true,
      },
      oAuth: {
        flows: {
          authorizationCodeGrant: true,
        },
        scopes: [OAuthScope.EMAIL, OAuthScope.OPENID, OAuthScope.PROFILE],
        callbackUrls: lazilyComputedCallbackUrls,
        logoutUrls: lazilyComputedCallbackUrls,
      },
      preventUserExistenceErrors: true,
    });
  };

  private createIdentityPool = (
    userPool: UserPool,
    userPoolClient: UserPoolClient,
  ) => {
    const identityPool = new IdentityPool(this, 'IdentityPool', {
      allowUnauthenticatedIdentities: true,
    });

    suppressRules(
      identityPool,
      ['CKV_AWS_366'],
      'Unauthenticated identities required for CloudWatch RUM telemetry from browser clients',
    );

    identityPool.addUserPoolAuthentication(
      new UserPoolAuthenticationProvider({
        userPool,
        userPoolClient,
      }),
    );

    return identityPool;
  };

  private createManagedLoginBranding = (
    userPool: UserPool,
    userPoolClient: UserPoolClient,
    userPoolDomain: CfnUserPoolDomain,
  ) => {
    new CfnManagedLoginBranding(this, 'ManagedLoginBranding', {
      userPoolId: userPool.userPoolId,
      clientId: userPoolClient.userPoolClientId,
      useCognitoProvidedValues: true,
    }).node.addDependency(userPoolClient, userPool, userPoolDomain);
  };

  private findCloudFrontDistributions = (): Distribution[] =>
    Stack.of(this)
      .node.findAll()
      .filter((child) => child instanceof Distribution);
}
