from contextlib import contextmanager

from strands import Agent, tool
from strands_tools import current_time

from wealth_management_portal_market_events_coordinator.theme_processor import (
    PortfolioThemeProcessor,
    ThemeProcessor,
)


# Theme processing tools
@tool
def process_market_themes(
    hours: int = 48,
    limit: int = 6,
    workgroup: str = "financial-advisor-wg",
    database: str = "financial-advisor-db",
    region: str = "us-west-2",
    profile_name: str = "wealth_management",
) -> dict:
    """
    DEPRECATED: Use web crawler's generate_general_themes instead.

    Process market themes from recent articles: identify, rank, and summarize.

    This tool performs the complete theme processing pipeline:
    1. Retrieves recent articles from Redshift
    2. Identifies 5-6 major themes using AI
    3. Ranks themes by importance (article count, source diversity, recency, keywords)
    4. Generates professional summaries for each theme
    5. Saves themes and associations to Redshift

    NOTE: This function is deprecated. Theme generation should be done by the web crawler
    on a schedule. Use get_market_themes() to query pre-generated themes instead.

    Args:
        hours: Number of hours to look back for articles (default: 48)
        limit: Maximum number of themes to return (default: 6)
        workgroup: Redshift workgroup name
        database: Redshift database name
        region: AWS region
        profile_name: AWS profile name

    Returns:
        Dictionary with processing results and theme details
    """
    try:
        processor = ThemeProcessor(
            workgroup=workgroup,
            database=database,
            region=region,
            profile_name=profile_name,
            bedrock_region="us-east-1",
            use_cross_region=True,
        )

        # Process themes
        themes, theme_articles_map = processor.process_themes(hours=hours, limit=limit)

        # Save to Redshift
        processor.save_themes_to_redshift(themes, theme_articles_map)

        # Format response
        themes_list = []
        for theme in themes:
            themes_list.append(
                {
                    "rank": theme.rank,
                    "theme_id": theme.theme_id,
                    "title": theme.title,
                    "sentiment": theme.sentiment,
                    "score": theme.score,
                    "article_count": theme.article_count,
                    "sources": theme.sources,
                    "summary": theme.summary,
                    "score_breakdown": theme.score_breakdown,
                }
            )

        return {
            "success": True,
            "themes_processed": len(themes),
            "themes": themes_list,
            "message": f"Successfully processed {len(themes)} market themes",
        }

    except Exception as e:
        return {"success": False, "error": str(e), "message": f"Theme processing failed: {str(e)}"}


@tool
def get_market_themes(
    limit: int = 10,
    hours: int = None,
    workgroup: str = "financial-advisor-wg",
    database: str = "financial-advisor-db",
    region: str = "us-west-2",
) -> dict:
    """
    Get existing general market themes from Redshift (query only - no generation).

    Themes are pre-generated by the web crawler on a schedule.

    Args:
        limit: Maximum number of themes to retrieve (default: 10)
        hours: Optional - only return themes generated in last N hours
        workgroup: Redshift workgroup name
        database: Redshift database name
        region: AWS region

    Returns:
        Dictionary with themes list
    """
    try:
        processor = ThemeProcessor(workgroup=workgroup, database=database, region=region)

        themes = processor.redshift.get_general_themes(limit=limit, hours=hours)

        themes_list = []
        for theme in themes:
            # Fetch articles for this theme
            articles = processor.redshift.get_theme_articles(theme.theme_id, "__GENERAL__")

            # Format articles with URLs
            articles_list = []
            for article in articles:
                articles_list.append(
                    {
                        "title": article.title,
                        "url": article.url,
                        "source": article.source,
                        "published_date": article.published_date.isoformat() if article.published_date else None,
                        "summary": article.summary,
                    }
                )

            themes_list.append(
                {
                    "rank": theme.rank,
                    "theme_id": theme.theme_id,
                    "title": theme.title,
                    "sentiment": theme.sentiment,
                    "score": theme.score if theme.score else 0,
                    "article_count": theme.article_count,
                    "sources": theme.sources,
                    "summary": theme.summary,
                    "articles": articles_list,
                }
            )

        return {
            "success": True,
            "themes_count": len(themes),
            "themes": themes_list,
            "message": f"Retrieved {len(themes)} market themes",
        }

    except Exception as e:
        return {"success": False, "error": str(e), "message": f"Failed to get themes: {str(e)}"}


# Portfolio theme processing tools
@tool
def process_portfolio_themes(
    client_id: str,
    portfolio_tickers: list[str] | None = None,
    generation_mode: str = "direct",
    min_relevance: int = 30,
    hours: int = 48,
    limit: int = 5,
    workgroup: str = "financial-advisor-wg",
    database: str = "financial-advisor-db",
    region: str = "us-west-2",
    profile_name: str = "wealth_management",
) -> dict:
    """
    DEPRECATED: Use web crawler's generate_portfolio_themes_for_client instead.

    Process portfolio-specific themes using direct generation or filtering approach.

    This tool can generate portfolio themes in two ways:
    1. "direct" mode (Approach 2): Filters articles by portfolio relevance first, then generates themes
       from those filtered articles. This produces purely portfolio-focused themes.
    2. "filter" mode: Takes existing general market themes and evaluates their relevance to the portfolio.

    Portfolio tickers are automatically fetched from Redshift based on the client's holdings.

    NOTE: This function is deprecated. Theme generation should be done by the web crawler
    on a schedule. Use get_portfolio_themes() to query pre-generated themes instead.

    Args:
        client_id: Client identifier (e.g., "CL00014")
        portfolio_tickers: Optional list of stock tickers (e.g., ["AAPL", "AMZN", "TSMC"]).
                          If not provided, will be fetched from client's holdings in Redshift.
        generation_mode: "direct" (generate from portfolio articles) or "filter" (filter general themes)
        min_relevance: Minimum relevance score 0-100 (default: 30) - used in filter mode
        hours: Look back period in hours (default: 48) - used in direct mode
        limit: Maximum number of themes to return (default: 5)
        workgroup: Redshift workgroup name
        database: Redshift database name
        region: AWS region
        profile_name: AWS profile name

    Returns:
        Dictionary with portfolio-specific themes
    """
    try:
        processor = PortfolioThemeProcessor(
            workgroup=workgroup,
            database=database,
            region=region,
            profile_name=profile_name,
            bedrock_region="us-east-1",
            use_cross_region=True,
        )

        # Process portfolio themes (tickers will be fetched if not provided)
        themes, theme_articles_map = processor.process_portfolio_themes(
            client_id=client_id,
            portfolio_tickers=portfolio_tickers,
            generation_mode=generation_mode,
            min_relevance=min_relevance,
            hours=hours,
            limit=limit,
        )

        # Get the actual tickers used (in case they were fetched)
        actual_tickers = portfolio_tickers
        if actual_tickers is None and themes:
            # Extract from first theme's matched_tickers or fetch again
            actual_tickers = processor.redshift.get_client_portfolio_tickers(client_id)

        # Save to Redshift
        processor.save_themes_to_redshift(themes, theme_articles_map)

        # Format response
        themes_list = []
        for theme in themes:
            # Fetch articles for this theme
            articles = processor.redshift.get_theme_articles(theme.theme_id, client_id)

            # Format articles with URLs
            articles_list = []
            for article in articles:
                articles_list.append(
                    {
                        "title": article.title,
                        "url": article.url,
                        "source": article.source,
                        "published_date": article.published_date.isoformat() if article.published_date else None,
                        "summary": article.summary,
                    }
                )

            themes_list.append(
                {
                    "rank": theme.rank,
                    "theme_id": theme.theme_id,
                    "client_id": theme.client_id,
                    "title": theme.title,
                    "sentiment": theme.sentiment,
                    "score": theme.score,
                    "relevance_score": theme.relevance_score,
                    "combined_score": theme.combined_score,
                    "matched_tickers": theme.matched_tickers,
                    "article_count": theme.article_count,
                    "sources": theme.sources,
                    "summary": theme.summary,
                    "relevance_reasoning": theme.relevance_reasoning,
                    "articles": articles_list,
                }
            )

        return {
            "success": True,
            "client_id": client_id,
            "generation_mode": generation_mode,
            "portfolio_tickers": actual_tickers or [],
            "themes_processed": len(themes),
            "themes": themes_list,
            "message": (
                f"Successfully processed {len(themes)} portfolio-specific themes"
                f" for {client_id} using {generation_mode} mode"
            ),
        }

    except Exception as e:
        return {"success": False, "error": str(e), "message": f"Portfolio theme processing failed: {str(e)}"}


@tool
def get_portfolio_themes(
    client_id: str,
    limit: int = 10,
    hours: int = None,
    workgroup: str = "financial-advisor-wg",
    database: str = "financial-advisor-db",
    region: str = "us-west-2",
) -> dict:
    """
    Get existing portfolio-specific themes from Redshift for a client (query only - no generation).

    Themes are pre-generated by the web crawler on a schedule.

    Args:
        client_id: Client identifier
        limit: Maximum number of themes to retrieve (default: 10)
        hours: Optional - only return themes generated in last N hours
        workgroup: Redshift workgroup name
        database: Redshift database name
        region: AWS region

    Returns:
        Dictionary with portfolio themes list
    """
    try:
        processor = PortfolioThemeProcessor(workgroup=workgroup, database=database, region=region)

        themes = processor.redshift.get_portfolio_themes(client_id=client_id, limit=limit, hours=hours)

        themes_list = []
        for theme in themes:
            # Fetch articles for this theme
            articles = processor.redshift.get_theme_articles(theme.theme_id, client_id)

            # Format articles with URLs
            articles_list = []
            for article in articles:
                articles_list.append(
                    {
                        "title": article.title,
                        "url": article.url,
                        "source": article.source,
                        "published_date": article.published_date.isoformat() if article.published_date else None,
                        "summary": article.summary,
                    }
                )

            themes_list.append(
                {
                    "rank": theme.rank,
                    "theme_id": theme.theme_id,
                    "client_id": theme.client_id,
                    "ticker": theme.ticker,  # Include ticker for per-stock themes
                    "title": theme.title,
                    "sentiment": theme.sentiment,
                    "score": theme.score if theme.score else 0,
                    "relevance_score": theme.relevance_score if theme.relevance_score else 0,
                    "combined_score": theme.combined_score if theme.combined_score else 0,
                    "matched_tickers": theme.matched_tickers if theme.matched_tickers else [],
                    "article_count": theme.article_count,
                    "sources": theme.sources,
                    "summary": theme.summary,
                    "relevance_reasoning": theme.relevance_reasoning if theme.relevance_reasoning else "",
                    "score_breakdown": theme.score_breakdown if theme.score_breakdown else None,
                    "articles": articles_list,
                }
            )

        return {
            "success": True,
            "client_id": client_id,
            "themes_count": len(themes),
            "themes": themes_list,
            "message": f"Retrieved {len(themes)} portfolio themes for {client_id}",
        }

    except Exception as e:
        return {"success": False, "error": str(e), "message": f"Failed to get portfolio themes: {str(e)}"}


@contextmanager
def get_agent(session_id: str):
    yield Agent(
        system_prompt="""
You are a Market Events Coordinator agent specializing in financial market intelligence.

Your capabilities:
1. Process general market themes from recent articles (identify, rank, summarize)
2. Process portfolio-specific themes by filtering general themes for client portfolios
3. Retrieve existing market themes and portfolio themes from the database
4. Provide insights on market trends and sentiment

Use your tools to:
- process_market_themes: Analyze recent articles and create ranked general market themes with summaries
- process_portfolio_themes: Filter general themes by portfolio relevance for a specific client
- get_market_themes: Retrieve existing general market themes from the database
- get_portfolio_themes: Retrieve portfolio-specific themes for a client
- current_time: Get the current date and time

When processing themes:
- General themes use client_id='__GENERAL__' and represent broad market trends
- Portfolio themes are client-specific and filtered by stock ticker relevance
- Themes are ranked by importance (score 0-100)
- Portfolio themes have both importance score and relevance score (combined score = 40% importance + 60% relevance)
- Each theme includes sentiment (bullish/bearish/neutral)
- Summaries are professional 2-3 sentence descriptions

Workflow:
1. First, run process_market_themes to create general market themes
2. Then, run process_portfolio_themes for each client to create portfolio-specific themes
3. Use get_market_themes and get_portfolio_themes to query existing themes

Always provide clear, actionable insights about market trends and portfolio relevance.
""",
        tools=[
            process_market_themes,
            process_portfolio_themes,
            get_market_themes,
            get_portfolio_themes,
            current_time,
        ],
    )
